export const CREATE_BOOK = "CREATE_BOOK";
export const CREATE_BOOK_SUCCESS = "CREATE_BOOK_SUCCESS";
export const LOAD_BOOKS_SUCCESS = "LOAD_BOOKS_SUCCESS";
export const UPDATE_BOOK_SUCCESS = "UPDATE_BOOK_SUCCESS";
export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
